
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true

vst-oauth:
  url: ${OAUTH2_URL}

vst-person:
  ribbon:
    listOfServers: ${IDENTITY_URL}

node:
  config:
    node-0:
      url: ${NODE_0_URL}
      xApiKey: ${NODE_0_API_KEY}
      nodeOwnerAddress: ${NODE_0_SENDER}
    node-1:
      url: ${NODE_1_URL}
      xApiKey: ${NODE_1_API_KEY}
      nodeOwnerAddress: ${NODE_1_SENDER}
    node-2:
      url: ${NODE_2_URL}
      xApiKey: ${NODE_2_API_KEY}
      nodeOwnerAddress: ${NODE_2_SENDER}

service:
  url: ${URL}

tx-observer:
  syncHistory: true
